import type {
  BusinessCorrespondent,
  DPRProject,
  TEVProject,
  SurveyProject,
  TrainingBatch,
  Beneficiary,
  TopBeneficiary,
  WorkflowTask,
  KnowledgeDocument,
  AIAssistant,
  CommandCenterMetrics,
} from "./types";

// ─── Command Center Metrics ──────────────────────────────────────────────────

export const commandCenterMetrics: CommandCenterMetrics = {
  banking: {
    activeBCs: 4287,
    onboardingTAT: 6.2,
    activeKiosks: 3814,
    monthlyVolume: 284500000,
  },
  consultancy: {
    liveDPRs: 23,
    liveTEVs: 17,
    pipelineValue: 145000000,
    avgDraftAge: 4.8,
  },
  training: {
    activeBatches: 68,
    totalBeneficiaries: 12480,
    certificationRate: 74.3,
    businessLaunchRate: 41.2,
  },
  network: {
    pooledProcurementSavings: 3200000,
    whiteLabelProducts: 12,
    enterpriseCohorts: 8,
    linkageConversions: 347,
  },
};

// ─── BC / Banking Data ───────────────────────────────────────────────────────

export const businessCorrespondents: BusinessCorrespondent[] = [
  {
    id: "BC001",
    name: "Ramesh Kumar Singh",
    mobile: "9876543210",
    district: "Lucknow",
    block: "Sarojini Nagar",
    bank: "State Bank of India",
    status: "active",
    kycScore: 92,
    activatedAt: "2024-03-15",
    lastTransactionAt: "2024-11-22",
    monthlyTransactions: 284,
    monthlyVolume: 1840000,
    kiosk: { gps: true, biometric: true, printer: true, active: true },
    fieldExecutive: "Anil Sharma",
    createdAt: "2024-03-01",
  },
  {
    id: "BC002",
    name: "Sunita Devi",
    mobile: "9765432109",
    district: "Varanasi",
    block: "Rajatalab",
    bank: "Punjab National Bank",
    status: "active",
    kycScore: 87,
    activatedAt: "2024-04-10",
    lastTransactionAt: "2024-11-21",
    monthlyTransactions: 198,
    monthlyVolume: 1230000,
    kiosk: { gps: true, biometric: true, printer: false, active: true },
    fieldExecutive: "Priya Yadav",
    createdAt: "2024-04-01",
  },
  {
    id: "BC003",
    name: "Mohan Lal Gupta",
    mobile: "9654321098",
    district: "Agra",
    block: "Khandoli",
    bank: "Bank of Baroda",
    status: "inactive",
    kycScore: 65,
    activatedAt: "2024-01-20",
    lastTransactionAt: "2024-09-01",
    monthlyTransactions: 12,
    monthlyVolume: 89000,
    kiosk: { gps: true, biometric: false, printer: true, active: false },
    fieldExecutive: "Rohit Verma",
    createdAt: "2024-01-10",
  },
  {
    id: "BC004",
    name: "Kavita Patel",
    mobile: "9543210987",
    district: "Kanpur",
    block: "Kalyanpur",
    bank: "Union Bank",
    status: "screening",
    kycScore: 78,
    kiosk: { gps: false, biometric: false, printer: false, active: false },
    fieldExecutive: "Suresh Mishra",
    createdAt: "2024-11-10",
    monthlyTransactions: 0,
    monthlyVolume: 0,
  },
  {
    id: "BC005",
    name: "Vikram Tiwari",
    mobile: "9432109876",
    district: "Prayagraj",
    block: "Naini",
    bank: "Canara Bank",
    status: "document",
    kycScore: 81,
    kiosk: { gps: true, biometric: false, printer: false, active: false },
    fieldExecutive: "Anil Sharma",
    createdAt: "2024-11-05",
    monthlyTransactions: 0,
    monthlyVolume: 0,
  },
  {
    id: "BC006",
    name: "Pooja Sharma",
    mobile: "9321098765",
    district: "Gorakhpur",
    block: "Sahjanwa",
    bank: "State Bank of India",
    status: "active",
    kycScore: 95,
    activatedAt: "2024-05-01",
    lastTransactionAt: "2024-11-22",
    monthlyTransactions: 412,
    monthlyVolume: 2670000,
    kiosk: { gps: true, biometric: true, printer: true, active: true },
    fieldExecutive: "Priya Yadav",
    createdAt: "2024-04-20",
  },
];

export const bcFunnelData = [
  { stage: "Leads", count: 847, color: "#6366F1" },
  { stage: "Screening", count: 612, color: "#8B5CF6" },
  { stage: "Documents", count: 438, color: "#EC4899" },
  { stage: "Interview", count: 294, color: "#F59E0B" },
  { stage: "Onboarding", count: 187, color: "#10B981" },
  { stage: "Active", count: 4287, color: "#059669" },
];

export const bcMonthlyTrend = [
  { month: "Jun", onboarded: 142, active: 3820 },
  { month: "Jul", onboarded: 168, active: 3940 },
  { month: "Aug", onboarded: 195, active: 4082 },
  { month: "Sep", onboarded: 178, active: 4194 },
  { month: "Oct", onboarded: 214, active: 4281 },
  { month: "Nov", onboarded: 89, active: 4287 },
];

// ─── DPR / Consultancy Data ──────────────────────────────────────────────────

export const dprProjects: DPRProject[] = [
  {
    id: "DPR001",
    title: "ODOP Cluster Development — Lucknow Leather",
    client: "MSME Department, UP",
    district: "Lucknow",
    sector: "MSME",
    value: 12500000,
    status: "in-review",
    draftAge: 3,
    assignedTo: "Dr. Sanjay Mishra",
    reviewLoops: 2,
    dueDate: "2024-12-05",
    createdAt: "2024-11-15",
  },
  {
    id: "DPR002",
    title: "Agri-Processing Infrastructure — Varanasi",
    client: "UP Agriculture Dept.",
    district: "Varanasi",
    sector: "Agriculture",
    value: 8200000,
    status: "draft",
    draftAge: 7,
    assignedTo: "Anjali Trivedi",
    reviewLoops: 0,
    dueDate: "2024-12-10",
    createdAt: "2024-11-01",
  },
  {
    id: "DPR003",
    title: "PM VISHWAKARMA Skill Center Setup",
    client: "MSDE",
    district: "Agra",
    sector: "Skilling",
    value: 4800000,
    status: "approved",
    draftAge: 0,
    assignedTo: "Rakesh Srivastava",
    reviewLoops: 3,
    dueDate: "2024-11-28",
    createdAt: "2024-10-20",
  },
  {
    id: "DPR004",
    title: "SHG Enterprise Cluster — Kanpur",
    client: "NRLM, UP",
    district: "Kanpur",
    sector: "SHG/Livelihood",
    value: 6300000,
    status: "revision",
    draftAge: 12,
    assignedTo: "Dr. Sanjay Mishra",
    reviewLoops: 4,
    dueDate: "2024-12-02",
    createdAt: "2024-10-25",
  },
  {
    id: "DPR005",
    title: "Tourism Infrastructure DPR — Prayagraj",
    client: "UP Tourism Dept.",
    district: "Prayagraj",
    sector: "Tourism",
    value: 15600000,
    status: "draft",
    draftAge: 2,
    assignedTo: "Ankita Gupta",
    reviewLoops: 1,
    dueDate: "2024-12-20",
    createdAt: "2024-11-18",
  },
];

export const tevProjects: TEVProject[] = [
  {
    id: "TEV001",
    title: "Food Processing Unit — Moradabad",
    applicant: "Rajesh Enterprises",
    loanAmount: 2500000,
    sector: "Food Processing",
    bank: "SBI",
    district: "Moradabad",
    status: "analysis",
    viabilityScore: 74,
    assignedTo: "Pradeep Kumar",
    dueDate: "2024-12-03",
    createdAt: "2024-11-10",
  },
  {
    id: "TEV002",
    title: "Textile Manufacturing — Kanpur",
    applicant: "Sharma Fabrics Pvt Ltd",
    loanAmount: 8000000,
    sector: "Textiles",
    bank: "PNB",
    district: "Kanpur",
    status: "data-collection",
    assignedTo: "Meena Singh",
    dueDate: "2024-12-08",
    createdAt: "2024-11-12",
  },
  {
    id: "TEV003",
    title: "Cold Storage Facility — Agra",
    applicant: "AgroFreeze Solutions",
    loanAmount: 12000000,
    sector: "Agriculture",
    bank: "Bank of Baroda",
    district: "Agra",
    status: "finalized",
    viabilityScore: 82,
    assignedTo: "Pradeep Kumar",
    dueDate: "2024-11-25",
    createdAt: "2024-10-28",
  },
];

// ─── Survey / Training Data ───────────────────────────────────────────────────

export const surveyProjects: SurveyProject[] = [
  {
    id: "SRV001",
    title: "Child Labour Survey — Eastern UP",
    scheme: "RAMP",
    district: "Varanasi",
    fieldAgents: 24,
    targetResponses: 5000,
    completedResponses: 3840,
    status: "active",
    startDate: "2024-11-01",
    endDate: "2024-12-15",
  },
  {
    id: "SRV002",
    title: "MSME Performance Baseline — UP",
    scheme: "MSME Survey",
    district: "Lucknow",
    fieldAgents: 18,
    targetResponses: 2500,
    completedResponses: 2500,
    status: "completed",
    startDate: "2024-09-01",
    endDate: "2024-10-31",
  },
];

export const trainingBatches: TrainingBatch[] = [
  {
    id: "BATCH001",
    batchCode: "YUVA-LKO-2411-01",
    scheme: "CM YUVA",
    district: "Lucknow",
    center: "UPICON Training Center, Hazratganj",
    trainer: "Ravi Shankar",
    totalEnrolled: 30,
    present: 28,
    assessmentScore: 76,
    startDate: "2024-11-04",
    endDate: "2024-11-29",
    status: "ongoing",
  },
  {
    id: "BATCH002",
    batchCode: "ODOP-VNS-2411-03",
    scheme: "ODOP",
    district: "Varanasi",
    center: "DIC Training Hall, Varanasi",
    trainer: "Geeta Devi",
    totalEnrolled: 25,
    present: 22,
    startDate: "2024-11-11",
    endDate: "2024-12-06",
    status: "ongoing",
  },
  {
    id: "BATCH003",
    batchCode: "SHAKTI-AGR-2410-02",
    scheme: "Mission Shakti",
    district: "Agra",
    center: "Block Training Center, Khandoli",
    trainer: "Sunita Yadav",
    totalEnrolled: 35,
    present: 35,
    assessmentScore: 81,
    startDate: "2024-10-07",
    endDate: "2024-11-01",
    status: "completed",
  },
  {
    id: "BATCH004",
    batchCode: "VSSY-KNP-2412-01",
    scheme: "VSSY",
    district: "Kanpur",
    center: "UPICON Kanpur Hub",
    trainer: "Manoj Singh",
    totalEnrolled: 28,
    present: 0,
    startDate: "2024-12-02",
    endDate: "2024-12-27",
    status: "upcoming",
  },
];

export const beneficiaries: Beneficiary[] = [
  {
    id: "BEN001",
    name: "Priya Verma",
    mobile: "9876512345",
    district: "Lucknow",
    scheme: "CM YUVA",
    batchId: "BATCH001",
    gender: "Female",
    age: 24,
    certificationStatus: "certified",
    businessLaunched: true,
    schemeLinked: true,
    loanAmount: 500000,
    turnover: 1200000,
    employeesCreated: 4,
    marketLinked: true,
    riskFlag: "none",
    lastContactAt: "2024-11-20",
  },
  {
    id: "BEN002",
    name: "Amit Tiwari",
    mobile: "9765423456",
    district: "Varanasi",
    scheme: "ODOP",
    batchId: "BATCH002",
    gender: "Male",
    age: 28,
    certificationStatus: "certified",
    businessLaunched: true,
    schemeLinked: false,
    loanAmount: 300000,
    turnover: 480000,
    employeesCreated: 2,
    marketLinked: false,
    riskFlag: "low",
    lastContactAt: "2024-11-18",
  },
  {
    id: "BEN003",
    name: "Meena Patel",
    mobile: "9654334567",
    district: "Agra",
    scheme: "Mission Shakti",
    batchId: "BATCH003",
    gender: "Female",
    age: 32,
    certificationStatus: "certified",
    businessLaunched: false,
    schemeLinked: true,
    marketLinked: false,
    riskFlag: "medium",
    lastContactAt: "2024-10-30",
  },
  {
    id: "BEN004",
    name: "Suresh Kumar",
    mobile: "9543245678",
    district: "Kanpur",
    scheme: "CM YUVA",
    batchId: "BATCH001",
    gender: "Male",
    age: 26,
    certificationStatus: "pending",
    businessLaunched: false,
    schemeLinked: false,
    marketLinked: false,
    riskFlag: "none",
    lastContactAt: "2024-11-22",
  },
];

export const topBeneficiaries: TopBeneficiary[] = [
  {
    rank: 1,
    id: "BEN001",
    name: "Priya Verma",
    district: "Lucknow",
    scheme: "CM YUVA",
    turnover: 1200000,
    repaymentHealth: "good",
    employeesCreated: 4,
    marketLinked: true,
    growthScore: 94,
  },
  {
    rank: 2,
    id: "BEN021",
    name: "Rahul Dubey",
    district: "Varanasi",
    scheme: "ODOP",
    turnover: 980000,
    repaymentHealth: "good",
    employeesCreated: 3,
    marketLinked: true,
    growthScore: 89,
  },
  {
    rank: 3,
    id: "BEN047",
    name: "Seema Agarwal",
    district: "Agra",
    scheme: "CM YUVA",
    turnover: 870000,
    repaymentHealth: "good",
    employeesCreated: 2,
    marketLinked: true,
    growthScore: 85,
  },
  {
    rank: 4,
    id: "BEN083",
    name: "Deepak Yadav",
    district: "Gorakhpur",
    scheme: "ODOP",
    turnover: 760000,
    repaymentHealth: "at-risk",
    employeesCreated: 1,
    marketLinked: false,
    growthScore: 71,
  },
  {
    rank: 5,
    id: "BEN102",
    name: "Anjali Gupta",
    district: "Prayagraj",
    scheme: "Mission Shakti",
    turnover: 690000,
    repaymentHealth: "good",
    employeesCreated: 3,
    marketLinked: true,
    growthScore: 82,
  },
];

// ─── Workflow Tasks ───────────────────────────────────────────────────────────

export const workflowTasks: WorkflowTask[] = [
  {
    id: "WF001",
    type: "bc-onboard",
    title: "BC Onboarding — Kavita Patel (BC004)",
    description: "Document verification and kiosk readiness check pending",
    assignedTo: "Suresh Mishra",
    priority: "high",
    status: "in-progress",
    dueDate: "2024-11-25",
    slaHours: 48,
    hoursElapsed: 36,
    createdAt: "2024-11-23",
    linkedEntityId: "BC004",
    linkedEntityType: "bc",
  },
  {
    id: "WF002",
    type: "dpr-review",
    title: "DPR Review — SHG Enterprise Cluster Kanpur",
    description: "4th review loop — revision required on financial projections",
    assignedTo: "Dr. Sanjay Mishra",
    priority: "critical",
    status: "pending",
    dueDate: "2024-11-24",
    slaHours: 24,
    hoursElapsed: 28,
    createdAt: "2024-11-22",
    linkedEntityId: "DPR004",
    linkedEntityType: "dpr",
  },
  {
    id: "WF003",
    type: "training-evidence",
    title: "Training Evidence Bundle — SHAKTI-AGR-2410-02",
    description: "Attendance sheets, assessment scores, and photo evidence",
    assignedTo: "Sunita Yadav",
    priority: "medium",
    status: "approved",
    dueDate: "2024-11-20",
    slaHours: 72,
    hoursElapsed: 48,
    createdAt: "2024-11-10",
    linkedEntityId: "BATCH003",
    linkedEntityType: "batch",
  },
  {
    id: "WF004",
    type: "tev-approval",
    title: "TEV Approval — Cold Storage Facility Agra",
    description: "Final sign-off required from Division Head",
    assignedTo: "Division Head — Consultancy",
    priority: "high",
    status: "pending",
    dueDate: "2024-11-26",
    slaHours: 48,
    hoursElapsed: 12,
    createdAt: "2024-11-24",
    linkedEntityId: "TEV003",
    linkedEntityType: "tev",
  },
];

// ─── Knowledge Documents ──────────────────────────────────────────────────────

export const knowledgeDocuments: KnowledgeDocument[] = [
  {
    id: "KD001",
    title: "BC Onboarding SOP — Master Guide v3.2",
    category: "SOP",
    tags: ["BC", "Onboarding", "Banking", "KYC"],
    division: "banking",
    createdAt: "2024-08-15",
    updatedAt: "2024-11-01",
    views: 847,
    author: "Banking Division",
  },
  {
    id: "KD002",
    title: "DPR Template — MSME Cluster Development",
    category: "Template",
    tags: ["DPR", "MSME", "Template", "Consultancy"],
    division: "consultancy",
    createdAt: "2024-06-20",
    updatedAt: "2024-10-15",
    views: 412,
    author: "Dr. Sanjay Mishra",
  },
  {
    id: "KD003",
    title: "CM YUVA Scheme — Eligibility and Franchise Guide",
    category: "Scheme",
    tags: ["CM YUVA", "Franchise", "Training", "Loan"],
    division: "training",
    createdAt: "2024-09-10",
    updatedAt: "2024-11-10",
    views: 1284,
    author: "Training Division",
  },
  {
    id: "KD004",
    title: "DPDP Compliance Checklist — Data Handling",
    category: "Compliance",
    tags: ["DPDP", "Compliance", "Data", "Privacy"],
    division: "common",
    createdAt: "2024-10-01",
    updatedAt: "2024-11-05",
    views: 328,
    author: "IT / Admin",
  },
  {
    id: "KD005",
    title: "TEV Appraisal Framework — Subsidy-Linked Projects",
    category: "Template",
    tags: ["TEV", "Appraisal", "Subsidy", "Finance"],
    division: "consultancy",
    createdAt: "2024-07-12",
    updatedAt: "2024-10-28",
    views: 567,
    author: "Pradeep Kumar",
  },
];

// ─── AI Assistants ────────────────────────────────────────────────────────────

export const aiAssistants: AIAssistant[] = [
  {
    id: "bc-assist",
    name: "BCAssist",
    description:
      "Hindi-first frontline assistant for BC agents — account opening, service menu, grievance routing, and lead monitoring.",
    division: "banking",
    icon: "🏦",
    color: "blue",
    capabilities: [
      "Account opening flow guidance",
      "RBI-compliant process cues",
      "Grievance routing",
      "Lead pipeline monitoring",
      "Field report generation",
      "Hindi language support",
    ],
    languages: ["Hindi", "English"],
  },
  {
    id: "dpr-copilot",
    name: "DPR Copilot",
    description:
      "Assembles first-draft DPRs from templates, prior sector work, and district data. Routes review comments through governed loops.",
    division: "consultancy",
    icon: "📋",
    color: "purple",
    capabilities: [
      "First-draft assembly from templates",
      "Sector benchmarking",
      "District data integration",
      "Review comment management",
      "Financial projection checks",
      "Submission readiness scoring",
    ],
    languages: ["English", "Hindi"],
  },
  {
    id: "tev-copilot",
    name: "TEV Copilot",
    description:
      "Guided appraisal workspace for cost, demand, viability, subsidy, and sensitivity analysis.",
    division: "consultancy",
    icon: "📊",
    color: "indigo",
    capabilities: [
      "Viability scoring",
      "Cost-benefit analysis",
      "Subsidy calculation",
      "Sensitivity analysis",
      "Bank format export",
      "Risk flag detection",
    ],
    languages: ["English"],
  },
  {
    id: "trainer-os",
    name: "Trainer OS",
    description:
      "Real-time training management — attendance, content delivery, quiz administration, and district-wise evidence.",
    division: "training",
    icon: "🎓",
    color: "green",
    capabilities: [
      "Attendance tracking",
      "Quiz administration",
      "Trainer prompts",
      "District evidence bundles",
      "Batch progress tracking",
      "Assessment scoring",
    ],
    languages: ["Hindi", "English"],
  },
  {
    id: "beneficiary-clone",
    name: "Beneficiary Clone",
    description:
      "Post-training assistant answering real beneficiary questions on wages, eligibility, product-market fit, and next steps in Hindi.",
    division: "training",
    icon: "🤝",
    color: "emerald",
    capabilities: [
      "Wage and salary guidance",
      "Scheme eligibility checks",
      "Product-market fit analysis",
      "Business basics in Hindi",
      "Next steps recommendation",
      "Government scheme navigation",
    ],
    languages: ["Hindi", "English"],
  },
  {
    id: "franchise-advisor",
    name: "Franchise Advisor",
    description:
      "Explains franchise models, compares sectors (food, FMCG, services), and helps borrowers evaluate Rs 5L collateral-free loan viability.",
    division: "training",
    icon: "🏪",
    color: "amber",
    capabilities: [
      "Franchise model comparison",
      "Sector analysis",
      "Loan viability assessment",
      "Trade-off analysis",
      "Business case guidance",
      "Market readiness check",
    ],
    languages: ["Hindi", "English"],
  },
  {
    id: "consulting-clone",
    name: "Consulting Clone",
    description:
      "Simple Hindi business advisor for MSMEs — profiling, branding, sales, packaging, compliance, and scheme fitment.",
    division: "consultancy",
    icon: "💡",
    color: "orange",
    capabilities: [
      "Business profiling",
      "Branding guidance",
      "Sales strategy",
      "Packaging recommendations",
      "Compliance checklist",
      "Scheme fitment analysis",
    ],
    languages: ["Hindi", "English"],
  },
  {
    id: "credit-prep",
    name: "CreditPrep",
    description:
      "Prepares borrowers and BCs for credit applications — document checklist, eligibility, and repayment planning.",
    division: "banking",
    icon: "💳",
    color: "cyan",
    capabilities: [
      "Document checklist",
      "Credit eligibility check",
      "Repayment planning",
      "Bank scheme matching",
      "Application guidance",
      "Nudge reminders",
    ],
    languages: ["Hindi", "English"],
  },
];

// ─── Chart Data ───────────────────────────────────────────────────────────────

export const trainingOutcomeData = [
  { month: "Jul", enrolled: 1240, certified: 880, launched: 480 },
  { month: "Aug", enrolled: 1480, certified: 1050, launched: 560 },
  { month: "Sep", enrolled: 1820, certified: 1320, launched: 720 },
  { month: "Oct", enrolled: 2100, certified: 1590, launched: 910 },
  { month: "Nov", enrolled: 1640, certified: 1180, launched: 680 },
];

export const districtBCDistribution = [
  { district: "Lucknow", active: 482, inactive: 64 },
  { district: "Varanasi", active: 398, inactive: 71 },
  { district: "Kanpur", active: 356, inactive: 48 },
  { district: "Agra", active: 312, inactive: 55 },
  { district: "Prayagraj", active: 298, inactive: 43 },
  { district: "Gorakhpur", active: 274, inactive: 38 },
];

export const consultancyPipelineData = [
  { name: "MSME", value: 45 },
  { name: "Agriculture", value: 22 },
  { name: "Skilling", value: 18 },
  { name: "Tourism", value: 8 },
  { name: "G2G PMU", value: 7 },
];

export const weeklyCommandData = [
  { day: "Mon", bcLeads: 42, dprActions: 8, trainingBatches: 12, workflows: 28 },
  { day: "Tue", bcLeads: 38, dprActions: 12, trainingBatches: 10, workflows: 24 },
  { day: "Wed", bcLeads: 55, dprActions: 7, trainingBatches: 15, workflows: 32 },
  { day: "Thu", bcLeads: 47, dprActions: 14, trainingBatches: 11, workflows: 29 },
  { day: "Fri", bcLeads: 62, dprActions: 9, trainingBatches: 18, workflows: 38 },
  { day: "Sat", bcLeads: 28, dprActions: 3, trainingBatches: 6, workflows: 14 },
];
